// =============================================================================
// CRAWL HISTORY CONTROLLER
// =============================================================================
// Handles the "select all" checkbox and "Delete Selected" button in the
// dashboard's crawl history panel (app/views/dashboard/_crawl_history.html.erb).
// =============================================================================

// `import { Controller } from "@hotwired/stimulus"` — named import of
// Stimulus's base Controller class, which this file's controller class
// will extend (inherit from) below.
import { Controller } from "@hotwired/stimulus"

// `export default class extends Controller { ... }` — an anonymous class
// (no name after `class`) that inherits from Stimulus's Controller and is
// this file's default export; app/javascript/application.js imports it and
// names it `CrawlHistoryController` when registering it under the
// "crawl-history" identifier. It attaches to the element with
// `data-controller="crawl-history"` in
// app/views/dashboard/_crawl_history.html.erb.
export default class extends Controller {
  // `static targets = [...]` declares this controller's "targets" — named
  // references to specific child elements inside this controller's HTML,
  // marked in the view with `data-crawl-history-target="selectAll"` etc.
  // `static` means this is a property on the CLASS itself (shared
  // configuration), not on individual controller instances. Declaring a
  // target named "selectAll" here makes Stimulus automatically generate
  // helper properties/methods like `this.selectAllTarget` (the single
  // matching element) and `this.hasSelectAllTarget` (whether one exists),
  // used further down in this file.
  static targets = ["selectAll", "rowCheckbox", "bulkDeleteButton"]

  // Called when the header "select all" checkbox is toggled
  // Wired up in the view via `data-action="change->crawl-history#toggleAll"`
  // on the header checkbox — meaning "when this checkbox's value changes,
  // call the toggleAll method on the crawl-history controller."
  toggleAll(event) {
    // `this.rowCheckboxTargets` (plural "Targets") is auto-generated by
    // Stimulus from the "rowCheckbox" entry in `static targets` above — it
    // returns an ARRAY of every element in this controller's scope marked
    // with `data-crawl-history-target="rowCheckbox"` (one per table row).
    // `.forEach(checkbox => { ... })` runs the given function for each one.
    this.rowCheckboxTargets.forEach(checkbox => {
      // `event.target` is the actual checkbox element the user clicked
      // (the "select all" header checkbox); `.checked` is its current
      // true/false state after the click. Setting every row checkbox's
      // `.checked` to match makes "select all" either check or uncheck
      // every row at once, depending on the header checkbox's new state.
      checkbox.checked = event.target.checked
    })
    // `}` closes the `.forEach(checkbox => { ... })` callback function.

    // Re-evaluates whether the "Delete Selected" button should be enabled,
    // now that every row's checked state may have just changed.
    this.refreshButtonState()
  }
  // `}` closes the `toggleAll(event) { ... }` method.

  // Called when any individual row checkbox is toggled
  // Wired up per-row via `data-action="change->crawl-history#toggleRow"` in
  // the view — no `event` parameter is used here since this method doesn't
  // need to know which specific checkbox fired the event, only that
  // something changed.
  toggleRow() {
    // If every row is checked, reflect that in the "select all" checkbox too
    // `this.hasSelectAllTarget` — auto-generated by Stimulus from the
    // "selectAll" target — is `true` only if an element with
    // `data-crawl-history-target="selectAll"` currently exists inside this
    // controller's scope. This guards against a crash if, for some reason,
    // the header checkbox isn't present (e.g. an empty crawl history list
    // renders no header row at all).
    if (this.hasSelectAllTarget) {
      // `this.selectAllTarget` (singular) is the one matching element
      // itself (Stimulus errors if there were zero or more than one match,
      // which is why `hasSelectAllTarget` is checked first here).
      // The assigned value spans two lines, joined by `&&` ("and"): both
      // conditions must be true for the header checkbox to end up checked.
      this.selectAllTarget.checked =
        // First condition: there must be at least one row checkbox to
        // begin with — an empty list shouldn't count as "all selected."
        this.rowCheckboxTargets.length > 0 &&
        // Second condition: `.every(...)` returns true only if EVERY row
        // checkbox in the array is currently checked.
        this.rowCheckboxTargets.every(checkbox => checkbox.checked)
    }
    // `}` closes the `if (this.hasSelectAllTarget) { ... }` block above.

    // Same follow-up as in toggleAll — the set of checked rows may have
    // just changed, so re-check whether the delete button should be enabled.
    this.refreshButtonState()
  }
  // `}` closes the `toggleRow() { ... }` method.

  // Enable "Delete Selected" only once at least one row is checked
  // A private-in-spirit helper method (not called directly from HTML via
  // data-action, just from the two methods above) that keeps the button's
  // enabled/disabled state in sync with the checkboxes.
  refreshButtonState() {
    // `.some(checkbox => checkbox.checked)` returns `true` as soon as it
    // finds AT LEAST ONE checked checkbox in the array (unlike `.every()`,
    // which requires ALL of them); returns `false` if none are checked.
    const anyChecked = this.rowCheckboxTargets.some(checkbox => checkbox.checked)
    // `this.bulkDeleteButtonTarget` is the single element matching
    // `data-crawl-history-target="bulkDeleteButton"` (the "Delete
    // Selected" button). Setting `.disabled = !anyChecked` means: disabled
    // (`true`) when nothing is checked, enabled (`false`) as soon as
    // something is checked — `!` flips the boolean.
    this.bulkDeleteButtonTarget.disabled = !anyChecked
  }
  // `}` closes the `refreshButtonState() { ... }` method.
}
// `}` closes the `export default class extends Controller { ... }` class
// definition that started at the top of the file.
